import os
import argparse
import pandas as pd
import matplotlib.pyplot as plt


# Define column names of Energy.log as generated by ./src/lte/model/lte-ue-rrc.cc
columns = ["timestamp", "IMSI", "CEL", "ER", "ERF"]


def get_opts():
    parser = argparse.ArgumentParser(description="Process and plot energy log data.")
    parser.add_argument("energy_log_path", type=str, help="Path to the Energy.log file.")
    parser.add_argument("--save", action="store_true", help="Flag to save plots to disk.")
    parser.add_argument("--save_path", type=str, default="plots", help="Path to save the plots.")
    args = parser.parse_args()
    return args


if __name__ == "__main__":
    args = get_opts()

    if not os.path.isfile(args.energy_log_path):
        raise FileNotFoundError(f"The file '{args.energy_log_path}' does not exist.")


    # Read the dataset into a pandas DataFrame
    data = pd.read_csv(args.energy_log_path, names=columns)

    # Convert timestamp to numeric for plotting
    data["timestamp"] = pd.to_numeric(data["timestamp"].str.replace("ns", "", regex=False))

    if args.save:    
        if not os.path.exists(args.save_path):
            os.makedirs(args.save_path)

    # Iterate through unique IMSI values and plot ER and ERF vs timestamp
    for imsi in data["IMSI"].unique():
        subset = data[data["IMSI"] == imsi]
        
        fig = plt.figure(figsize=(10, 5))
        plt.plot(subset["timestamp"], subset["ER"], label="ER", marker="o")
        
        plt.xlabel("Timestamp (ns)")
        plt.ylabel("Values")
        plt.title(f"Energy Remaining vs Timestamp for IMSI {imsi}")
        plt.legend()
        plt.grid(True)
        plt.tight_layout()

        if args.save:
            save_path = os.path.join(args.save_path, f"energy_log_{imsi}.png")
            plt.savefig(save_path)
        else:
            plt.show()

        plt.close(fig)


    # Iterate through unique IMSI values and plot one ERF vs timestamp

    fig = plt.figure(figsize=(10, 5))
    for imsi in data["IMSI"].unique():
        subset = data[data["IMSI"] == imsi]       
        plt.plot(subset["timestamp"], subset["ERF"], label=f"IMSI {imsi}")
        
    plt.xlabel("Timestamp (ns)")
    plt.ylabel("Values")
    plt.title(f"Energy Remaining Fraction vs Timestamp")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()

    if args.save:
        save_path = os.path.join(args.save_path, f"energy_fraction_log_{imsi}.png")
        plt.savefig(save_path)
    else:
        plt.show()

    plt.close(fig)

