#ifndef POLY_PREDICTOR_H
#define POLY_PREDICTOR_H

#include <cmath>
#include <random>
#include <array>

/**
 * The code simulates the generation of energy by solar panels.
 * The average energy $E_m$ is generated by a 6th degree polynomial obtained
 * from real data (at https://github.com/kaivalpanchal/Solar-Panel-Power-Generation) and its coefficients are stored in `coefs`.
 * We also consider the variation every second stored in `sigmas`.
 * Thus the value returned by `predict` consists of a value taken from a
 * normal distribution with mean $E_m$ and variance sigma (obtained from the second closest to the value of x).
 *
 * Note: x is a real number that represents a time between 0 and SECONDS_IN_A_DAY seconds. NUM_SEC_DAY is the total number of seconds in a day.
 */


constexpr int POLY_DEGREE = 6;
# define SECONDS_IN_A_DAY 86400

struct PolyPredictor {

    PolyPredictor();

    double predict_sample(double t) const;

    double areaUnderCurve(double t);

    void setSeed(long unsigned int new_seed);
    void setPeakValue(double peak_value);
    void setSigmaScale(double new_sigma_scale);

    void next(void);
    void next(double new_peak_value);  // change the profile of the predictor, including the new peak

  private:
    // coeficients of the polynomial regression
    std::array<float, POLY_DEGREE + 1> coefs = {4.461134735697436e-27, -1.1842160751871317e-21, 1.2978113596353051e-16, -7.508286355968874e-12, 2.3908177024357847e-07, -0.0038757498028134524, 24.712879835452856};

    // values generated by fit_poly.py
    const double xmin = 20701.0;
    const double xmax = 67500.0;
    double peak_y = 1;
    double scale_y = 1;
    double scale_sigma = 1;
    long unsigned int seed = 42;

    double predict(double x) const;
    double evaluateIntegralAt(double x);
};

#endif
