import argparse
import pandas as pd
import matplotlib.pyplot as plt

from utilities import find_files


def read_log_file(log_filename: str) -> pd.DataFrame:
    # Load the log file
    df = pd.read_csv(log_filename, header=None)

    # Assign column names
    df.columns = ['event', 'imsi', 'local_address', 'source_address', 'protocol', 'packet_size', 'timestamp']

    # Convert timestamp to float
    df['timestamp'] = df['timestamp'].astype(float)

    # Sort by timestamp
    df = df.sort_values(by='timestamp')

    # Calculate accumulated packet size per IMSI
    df['accumulated_size'] = df.groupby('imsi')['packet_size'].cumsum()

    # Get the max timestamp across all data
    max_timestamp = df['timestamp'].max()

    # Pad each IMSI with a final row to extend the curve
    padded_rows = []
    for imsi, group in df.groupby('imsi'):
        last_row = group.iloc[-1].copy()
        if last_row['timestamp'] < max_timestamp:
            last_row['timestamp'] = max_timestamp
            padded_rows.append(last_row)

    # Add padding rows to original DataFrame
    if padded_rows:
        df = pd.concat([df, pd.DataFrame(padded_rows)], ignore_index=True)

    # Sort again after padding
    df = df.sort_values(by=['imsi', 'timestamp'])


    return df


def plot_receive(df, show: bool = False):
    plt.figure(figsize=(10, 6))
    for imsi, group in df.groupby('imsi'):
        # plt.plot(group['timestamp'], group['accumulated_size'], label=f'IMSI {imsi}')
        plt.step(group['timestamp'], group['accumulated_size'], where='post', label='eNB' if imsi == 0 else f'IMSI {imsi}')


    plt.title('Accumulated Packets vs Time')
    plt.xlabel('Time (seconds)')
    plt.ylabel('Accumulated Size (bytes)')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    if show:
        plt.show()
    else:
        plt.savefig(log_filename.replace('.log', '.png'))
    plt.close()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Parse receive log file. Generated by ueLteDevice->SetReceiveCallback() in the scenario code.")
    parser.add_argument("--dir", type=str, default=None, help="Folder to search for log files")
    parser.add_argument("--fname", type=str, default=None, help="Name of the log file to process")
    parser.add_argument("--show", action="store_true", help="Show the plot")
    args = parser.parse_args()

    log_filename = 'logs/markov/u4_t180000000000_c0_e0/31_07_2025_11_00_10/w0_s1_receive.log'

    if args.dir is not None:
        state_change_files = find_files(args.dir, target_suffix="_receive.log")
        print("Found state change files:")
        for file in state_change_files:
            print(file)

    elif args.fname is not None:
        df = read_log_file(args.fname)  # read the log to a dataframe
        plot_receive(df, show=args.show)

    else:
        print("Please provide either a directory or a file name to process.")
        parser.print_help()
        exit(1)
