import pandas as pd
import matplotlib.pyplot as plt
import re


def read_log(log_file):
    # Load and parse log
    data = []

    # Regular expression to parse each line
    pattern = r'StartTxDataFrame: size (\d+), npackets (\d+), duration \+(\d+)ns, node (\d+)'

    with open(log_file, 'r') as f:
        timestamp = 0  # initialize cumulative time in seconds
        for line in f:
            match = re.search(pattern, line)
            if match:
                size = int(match.group(1))
                npackets = int(match.group(2))
                duration_ns = int(match.group(3))
                node = int(match.group(4))
                duration_s = duration_ns / 1e9
                timestamp += duration_s  # accumulate time
                data.append({'time': timestamp, 'node': node, 'size': size, 'npackets': npackets})

    # Create DataFrame
    df = pd.DataFrame(data)

    return df


"""
    This scripts reads a log file created from the NS_LOG.
    The data is generated by `LteSpectrumPhy::StartTxDataFrame`.
    You need to enable it using `ns3::LogComponentEnable ("LteSpectrumPhy", LOG_LEVEL_INFO);`.

"""

if __name__ == '__main__':
    show = False
    log_file = 'test.log'  # replace with your actual filename
    df = read_log(log_file)

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 10), sharex=True)

    # Plot npackets
    for node, group in df.groupby('node'):
        ax1.plot(group['time'], group['npackets'], drawstyle='steps-post', label=f'Node {node}')
    ax1.set_ylabel('Number of Packets')
    ax1.set_title('Number of Packets Over Time')
    ax1.legend()
    ax1.grid(True)

    # Plot size
    for node, group in df.groupby('node'):
        ax2.plot(group['time'], group['size'], drawstyle='steps-post', linestyle='--', label=f'Node {node}')
    ax2.set_xlabel('Time (s)')
    ax2.set_ylabel('Packet Size (bytes)')
    ax2.set_title('Packet Size Over Time')
    ax2.legend()
    ax2.grid(True)

    ax1.legend(loc='center left', bbox_to_anchor=(1.0, 0.5), title='Legend')
    ax2.legend(loc='center left', bbox_to_anchor=(1.0, 0.5), title='Legend')

    plt.tight_layout()
    if show:
        plt.show()
    else:
        img_fname = log_file.replace('.log', '.png')
        print("Saved plot to", img_fname)
        plt.savefig(img_fname)
    plt.close()
